server:
   port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eurka-zuul
zuul:
  routes:
    api-ribbon:
      path: /api-ribbon/**
      serviceId: eureka-ribbon
    api-feign:
      path: /api-feign/**
      serviceId: eureka-feign
logging:
  level:
    root: INFO