server:
   port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eurka-feign
feign:
  hystrix:
    enabled: true
logging:
  level:
    root: INFO